[toolchain]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/dev-wallet1.json"

[programs.localnet]
reputation = "J9X4dDqyFL2pG3MZJn4WEEK3Mcku9nG8XJcEo8zB9z2"

[programs.devnet]
reputation = "J9X4dDqyFL2pG3MZJn4WEEK3Mcku9nG8XJcEo8zB9z2"
