[toolchain]
channel = "1.95.0-nightly"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/dev-wallet1.json"

[programs.localnet]
escrow = "F2Fx88Qovf28dqhPLomxTuFNa1fm2VBnkJdksqQrQs8N"

[programs.devnet]
escrow = "F2Fx88Qovf28dqhPLomxTuFNa1fm2VBnkJdksqQrQs8N"

[programs.mainnet-beta]
escrow = "F2Fx88Qovf28dqhPLomxTuFNa1fm2VBnkJdksqQrQs8N"
